### ISSUE TITLE
libosmscout support

### ISSUE THREAD

**Issue by Caballlero** [rinigus/osmscout-server#108]
Hi rinigus
I'm worried about the possible abandonment of libosmscout in your app. I'm really fan of libosmscout  and I'm fine with the work you've done. What is your discontent about libosmscout ?

**Comment by rinigus** [comment]
Do not worry, I am not leaving libosmscout at all! Its gonna be supported as it is and I will try to contribute to libosmscout as much as I can to it. Since the server architecture allows you to choose the backend, it will be simple to select libosmscout as a backend as it is now. So, all I am doing is expanding it a bit further, not by any means removing it.

By looking into how rendering is done in other libs and bringing these over, I would like to learn about it as well. Hopefully, I can later use this experience to enhance rendering in libosmscout.

I guess for these discussions, TMO is a bit better forum?

**Comment by Caballlero** [comment]
ok 
- So I understand you are not trying to abandon libosmscount, just play with other renderings and then learn and apply them to libosmscount oh for a new project.
- You have made an excellent work/server.
- I think the only thing that needs to osmscout-server
 is to have MORE poi, this is in your hands oh in the hands of open street maps, poi is very very important?
