### ISSUE TITLE
mapnik: add night stylesheet

### ISSUE THREAD

**Issue by rinigus** [rinigus/osmscout-server#135]
The stylesheet for night mode is missing for mapnik backend.

**Comment by rinigus** [comment]
style ready, now just have to hook it to the server

**Comment by Caballlero** [comment]
Hey rinigus , i know this issue is closed, but i want know if exist the posibility to add night stylesheet automatic  based at time? or need to do manual?

thanks

**Comment by rinigus** [comment]
Hi @Caballlero, no worries, we can still discuss it here.

The server now checks which style is requested by the client (day or night, for example) and renders the tiles accordingly. So, on the server side you don't have to choose anything.

Decision on whether show day or night tiles has to come from the client since the client also caches the tiles. Making that automatic would be great and I was planning to ask Poor Maps and modRana developers for it.

**Comment by Caballlero** [comment]
I would like this features with modrana, i like modrana rinigus , because have a better gui , you know the routing line of modrana it pretty, when i do zoom in the map the routing line  look perfect, but in poormaps ,look like that routing line moving not stay in the correct street , you know right?  THANK YOU RINIGUS - FOR YOU DOING A GOOD WORK.
