### ISSUE TITLE
Server side tile cache

### ISSUE THREAD

**Issue by Thra11** [rinigus/osmscout-server#151]
I think there could be a number of benefits if osm scout server could cache the tiles it has rendered. (I don't believe osm scout server currently does this, but I may be wrong)

1. Accurate cache invalidation: The server knows when either the map data is updated, or the stylesheet or other rendering settings have changed, so it knows exactly when tiles need to be discarded or rerendered. By contrast, a client such as poor maps can only discard tiles based on metrics such as tile age/time since tile was last used.
2. Cache sharing between multiple clients: e.g. any tiles requested by poor maps will be ready in the cache if modrana wants them. Both clients can benefit from caching without storing duplicates.

**Comment by rinigus** [comment]
I do see the points and they are absolutely valid. Few notes though:

* The clients use different sizes of the tiles. Poor Maps asks for larger tiles since its much more optimal to render them. modRana is currently limited to 256x256 and upcoming Mæp support may have some other size. So, caching would have to take that into account.

* Clients all do have caches already since they use them for online providers. So, we would be duplicating the functionality that is already there (although not shared and easily invalid tiles could creep into clients)

* In practice, I would expect users to stick to the client they like and the backend they like. After initial configuration, the caches should start serving their purpose.

* We have to think about how future-proof these modifications are. While still without any consensus, vector tiles using OpenGL are coming. So, we should be ready to start delivering those to the clients and bundle (if needed) with the vector styles. See for example https://mapzen.com/products/tangram/ and QtLocation support for Mapbox ( https://doc-snapshots.qt.io/qt5-5.9/location-plugin-mapboxgl.html ). As soon as these maps are in, all caching is not needed anymore. So, its probably better to focus first on things that are gonna stay. Btw, developing styles is still investment since "translation" of styles should be significantly simpler than its development.

**Comment by Thra11** [comment]
I wasn't aware they used different sized tiles (although now I see there's a scale parameter in the API). Combined with the eventual obsolescence due to MapBoxGL, I agree that work and added complexity aren't worthwhile. I will close the issue.

**Comment by rinigus** [comment]
We can always reopen it if we re-evaluate it in future.
