### ISSUE TITLE
Guatemala country look deformed in  any preliminary view :  \

### ISSUE THREAD

**Issue by Caballlero** [rinigus/osmscout-server#166]
- Observed the issue from modrana-osmScont-server-v0.13.1-1>libosmscount>Geocoder-NLP.
The country has to be seen in defined lines from the borders to differentiate each country.
In  this case the lines to define lines from the borders look to poors.
![20170709165347](https://user-images.githubusercontent.com/24536606/27997511-7337674c-64c7-11e7-8485-bd324651bfb8.jpg)

**Comment by rinigus** [comment]
Hi! libosmscout backend does not draw borders with the current settings, as far as I remember. So, you observe the data that is recorded for Guatemala and polygons extending from the country, as expected for this import. When using Mapnik, boundary is not plotted either which indicates that there was some problem with importing it (I have seen it before for few other countries as well). I will look into fixing Mapnik case. As for libosmscout, that would have to wait for a while. I would prefer to support as much as I can one combination of the backends and improve other aspects of map usage.

**Comment by Caballlero** [comment]
Hello: Rinigus 
First at all, sorry for late reply. I am practically reopening this problem, because i do not like to see my country deformed :  ) and worselly being  to one of my favorite app osmscont-server. Also I have a query why the karry maps are not deformed being the same uptreams? if karry have the  antidote of this problem why not asking for  it and fix it ?

Thanks ...  Also-the wizard feature of this, looking good rinigus. :  )

**Comment by rinigus** [comment]
No problem with re-opening. So, when I look on Karry's OSM Scout, I get the image like attached. This looks similar, with exception of World coastline. 

Is it the absence of coastlines that is disturbing?

Additional question, have you tried Mapnik backend? That should have all coastlines present.

![20170715204824](https://user-images.githubusercontent.com/15706605/28241804-393c0d5e-69a4-11e7-9fa2-5e6df6ad47d6.jpg)

**Comment by Caballlero** [comment]
Hi Rinigus 
I updated all the map with the new release osm-scont-server -v 0.14.  Same look deformed in mapnik too. : /

**Comment by Caballlero** [comment]
I will RE-check the maps of @Karry ,if it is deformed too. I deleted the  @Karry maps a week ago to see if it work with your maps , but not work. then i need download the map again to see if is deformed .I REMEMBER THAN KARRY MAP HAVE FIXED. I WILL LET YOU KNOW SHORTLY.

**Comment by rinigus** [comment]
Hi, I think that I may understand what you mean with the "deformed" country. The extract that is called Guatemala contains geo-data covering Guatemala as well as few other data corresponding to the features that go out of the country. For example, a piece of a road, river, and so on. The reasons are explained at http://blog.geofabrik.de/?p=397 and its exactly the same settings are used to import planet.pbf into OSM Scout Server. Due to these reasons, the import will stay the same way and just please be aware that it will stay as it is.

The missing border around Guatemala in Mapnik is another issue. I have seen it for few countries and would have to figure out why it is so. I'll open another issue regarding the border.

**Comment by rinigus** [comment]
Since Guatemala dataset contains data from other countries as well, I assume that the issue can be closed. Re-open if I misunderstood you.
