### ISSUE TITLE
Update es-ES.json (valhalla project)

### ISSUE THREAD

**Issue by carmenfdezb** [rinigus/osmscout-server#183]
I've fixed some texts for the Spanish language in valhalla project: https://github.com/valhalla/valhalla/pull/905
Could you add them in the next version?
Thanks in advance!

**Comment by rinigus** [comment]
Sure and thanks for fixing it! I will have to wait for the next valhalla release that would include your patches. That would allow me to build valhalla routing module and release it. In general, they do release frequently, so I don't think we have to wait for long.

**Comment by Caballlero** [comment]
Again this translator modifying the spanish in a static and selfish way. I totally disagree She says that it is fixing but the truth is not fixing this modifying a correct spanish already existing.

**Comment by Caballlero** [comment]
I totally disagree with this. She is not **fixing** her is **modifying **on an existing correct spanish.

**Comment by carmenfdezb** [comment]
What are you saying, @Caballlero? Did you read the text I've fixed? Really?
Please, don't follow me, and don't disturb anymore.
Thanks in advance!

**Comment by rinigus** [comment]
@Caballlero, please note that these changes are the ones done in valhalla upstream and were merged after review by the team behind valhalla. In this issue, I was just notified about them and its good for me to know about due to the packaging for SFOS.

I am not in position to judge about the translation. I presume that Valhalla team, since they are based in US, have much bigger exposure to Spanish than me. However, please note es-ES stands for Spanish as in Spain. For Spanish as in other countries, use es-XXXX with XXXX replaced as required.

**Comment by rinigus** [comment]
Valhalla 2.3.6 is released and I updated the routing module.
