### ISSUE TITLE
Day/night view switching

### ISSUE THREAD

**Issue by a-dekker** [rinigus/osmscout-server#199]
As you are working on making OSMscout server more user friendly (like automatically starting when needed) I was wondering about an automatic day/night mode.
Now you need to select OSM day or night view in the routing app first.
My idea would be that OSMscout would switch data output according to dusk/dawn (if activated in the settings). Tools like sunwait can calculate this for you. You would only need the current geo location for this, but GPS needs to be activated anyway if you want to route.

It's only a nice to have, and I might be missing some other hurdles.

**Comment by rinigus** [comment]
:) I actually had similar idea earlier and wrote it down as an issue in my branch of Poor Maps: https://github.com/rinigus/poor-maps/issues/2 . 

Its a client that would have to ask for day/night maps. This is due to caching that is performed by the clients to speed up showing the maps, we would need to make separate caches for day and night and switch between them. 

I will look into it a bit later, have some other things to finish first

**Comment by rinigus** [comment]
Since its not really server's issue, I am closing it. We can pursue it under client(s)
