### ISSUE TITLE
"Custom" profile does allow for too little customisation

### ISSUE THREAD

**Issue by Olf0** [rinigus/osmscout-server#243]
**Background:**
I am using the profile *libosmscout with Geocoder-NLP* in OSM Scout Server with Poor Maps and modRana for a long time to my full satisfaction.  Hence libosmscout is used for maps and routing, which is working well.  I refrained from trying Mapnik maps, Valhalla or the Font Module in the past due to their size.

For testing vector maps served by OSM Scout Server with WhoGo Maps and Laufhelden, I just wanted to add these to the selected profile.  Unfortunately this does not seem to be feasible in OSM Scout Server's GUI, currently.

Now that I know that mapboxgl-qml is working on Jolla 1 phones, I would like to use libosmscout for raster tiles (serving modRana, Poor Maps and the pure data OSM Scout), vector tiles for WhoGo Maps and Laufhelden, NLP parsing and either (at my choice) libosmscout or Valhalla for routing.

**Abstraction**
Taking a step back from my specific use case, OSM Scout Server currently supports:
* Two providers for offline raster tiles: libosmscout and Mapnik
* One provider for offline vector tiles.
* Two routing providers: libosmscout and Valhalla
* One NLP parsing provider

**Feature suggestion:**
Please make the "Custom" profile allowing for any choice of aforementioned four options (out of {None, choice A, eventually choice B etc.} for raster maps, vector maps, routing and NLP parsing).

**Comment by rinigus** [comment]
@Olf0, there is a "Custom" profile. When you select it, you will have to:

* Specify what data do you want to have on the device in Map Manager
* Specify preference for the backend in Settings (rendering of raster tiles, geocoding, and routing). No need to specify anything regarding Mapbox since it is served if available and requested.

However, if you are already using MapboxGL and GeocoderNLP, I would suggest to use Valhalla as router as well. Valhalla, just by itself, is usually smaller in terms of space when compared to libosmscout (Valhalla needs to keep only routing data), is faster, and able to route between countries.

**Comment by Olf0** [comment]
@rinigus, thanks for the quick reply.
> [...] there is a "Custom" profile. 

I know, but ...

> When you select it, [...]

... did not understand how it works.

> However, if you are already using MapboxGL and GeocoderNLP, I would suggest to use Valhalla as router as well. Valhalla, just by itself, is usually smaller in terms of space when compared to libosmscout (Valhalla needs to keep only routing data), is faster, and able to route between countries.

But for now I still want to keep raster tiles working, hence having libosmscout's maps installed anyway.  Thus Valhalla needs *additional* space in my case.

**Comment by rinigus** [comment]
I hope that you use SD Card to keep the maps. This resolves most of the pain, I think.
