### ISSUE TITLE
how to update a map

### ISSUE THREAD

**Issue by legacychimera247** [rinigus/osmscout-server#248]
unfortunately osm is lacking lot of streets in my area so i started adding them via the osm website...

they are now present in osm web map but how to update the map on osmscout?cause the map manager always report there is no update for the maps

**Comment by rinigus** [comment]
Excellent! The maps are updated by me and I expect to start new import process at the end of April. It involves converting maps to corresponding formats (may take a week for Planet) and distributing them to the servers that are used by the application to get the updates. So, all you can do now, is to wait a bit.

I am closing an issue, since its by design. But we can discuss it in the closed state as well, if you wish

**Comment by rinigus** [comment]
Sure. I try to do it once in 2 months. Last time was the end of February/beginning od March, so its time to do that.

**Comment by legacychimera247** [comment]
Good...so thanks for your effort :)

Il Lunedì 16 aprile 2018, rinigus scrive:
> Sure. I try to do it once in 2 months. Last time was the end of February/beginning od March, so its time to do that.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.￼
>

-- 
Inviato dal mio Jolla

**Comment by legacychimera247** [comment]
reopening this one...downloaded 600 mb update to find out maps are still the same, even if i completely redone my city...where you just rebuilding the maps with latest update or i am missing something? :)

**Comment by rinigus** [comment]
Good morning!

Please send me an example street or some other object, so I could check the import. Ideally openstreetmap URL. Feel free to email directly for privacy.

**Comment by legacychimera247** [comment]
i would do it, but i cannot find an email adress :)

**Comment by legacychimera247** [comment]
well i think we can close this one right? :)

**Comment by rinigus** [comment]
I think so :)
