### ISSUE TITLE
[question] Import Maps from OSMScout client to OSMScout Server

### ISSUE THREAD

**Issue by zwieberl** [rinigus/osmscout-server#294]
Hi,
this might probably be answered somewhere already, but I couldn't find it:
I have been using OSMScout (client) for some time now and downloaded quite a substantial amount of card material.
Is it possible to import those into OSMScout Server to switch gracefully to Pure Maps without the need to download everything again? 
I have set the card directory in OSMScout Server to that directory, but it doesn't seem to find them automatically. 
I redownloaded one country, which then worked in both server and client. So I'm assuming the format is identical.
Thanks!

Edit: Forgot to mention: System is Sailfish 3.0.0.8. OSMScout client 1.2.0 from harbour, OSMScout Server 1.13.0

**Comment by rinigus** [comment]
Hi! No, unfortunately you cannot. OSM Scout Server has this name due to its start when it was mainly using the same library as Karry's OSMScout application. These days, the server is mainly developed on the basis of other libraries - Mapbox, Valhalla, and GeocoderNLP. These store data in completely different format and cannot share the data with OSMScout. Even the backend versions from the same original library (libosmscout) are not probably shared since versions of the library are very much different.

So, start with the small downloads and see if you like it. Note that also maps are updated regularly (for the both applications OSMScout and OSM Scout Server) and may introduce some new features. In this respect, be ready to redownload on update of the maps.

**Comment by rinigus** [comment]
Closing since its not an issue as such, feel free to discuss even with the closed issue. Or at talk.maemo.org.

**Comment by zwieberl** [comment]
Thanks for the quick and extensive answer! Already decided to switch. Pure maps is just so much faster.
