### ISSUE TITLE
crash with the borders style

### ISSUE THREAD

**Issue by rinigus** [rinigus/osmscout-server#61]
To reproduce:

select border style for map drawing

any tile drawing would crash the server on sailfish

**Comment by Karry** [comment]
Hi. What database and code versions are you using? I was searching this bug few hours and found problem in this commit https://github.com/Framstag/libosmscout/commit/24190d807c361ee8dea05eb19bd4a2d2f1b961a8#diff-9c14d9bcb723e12295159e4c0281ba9aR1306 that change disk size of `AdminLevelFeatureValue`. It is not backward compatible change, but we don't increase data version with it! @Framstag be careful with such changes please. 

So, when you have map generated with Importer without this commit and tries to load it with it, it will be broken. Otherwise too. Problem is that I already generated some maps on my server with this commit and released OSMScout with it too. It creates dangerous mix of versions when every touch to AdminLevelFeature may lead to app crash...

I am trying to maintain branches with backward compatibility, but I will add warning dialog to my app when user uses older database version...

**Comment by rinigus** [comment]
@Karry , BRILLIANT CATCH! I have seen crashes with mixed IsIn databases/libraries, but didn't connect them! Don't know which version I was using, since there was a mixture of maps from the work on new geocode. Taking the latest map version that I generated few days ago as a part of generation of the location databases to cover the world, fixed the problem. 

So, we should increase the version number for the map database. Note that there was some work proposed on changes of the border (FileWriter::MAX_NODES), maybe these can be merged. 

@Karry, thank you again for pointing to the fix!

**Comment by Framstag** [comment]
Sorry, I was obviously not aware enough that could break existing code.

**Comment by rinigus** [comment]
Fixed in libosmscout with the increase of the dataset version.
