### ISSUE TITLE
Problematic string

### ISSUE THREAD

**Issue by d9h20f** [rinigus/osmscout-server#68]
The string "At crossing (%crossingway%), %turncommand%" is difficult to translate, because in some languages the (most) correct way of saying it is "Turn at crossing x right". If you could split the "%turncommand%" string so it could be spread across the sentence, that would be great.

**Comment by rinigus** [comment]
Thank you for suggestion! I'll look into it.

**Comment by rinigus** [comment]
OK, it looks that this string is used only in the verbose instructions. So far, Poor Maps has not been displaying them and it should be invisible for the user (haven't tried modRana since I am not able to run it on my device due to a bug in modRana). It's not gonna be simple to replace the string, but I will look into it a bit later.

**Comment by d9h02f** [comment]
If it's too difficult, it shouldn't be a problem to work around it by translating it slightly different, so don't worry too much about it.

**Comment by rinigus** [comment]
Thank you! Let's keep the issue open and hope to come back to it later.

**Comment by rinigus** [comment]
Dropping old libosmscout issues, no time to address them. Can be reopened later if someone wants to maintain this backend.
