### ISSUE TITLE
difficulties downloading maps and postal info

### ISSUE THREAD

**Issue by a-dekker** [rinigus/osmscout-server#89]
Using a Jolla 1 (1GB) I am having difficulties with the downloads.
The map download keeps on giving timeouts and the postal part as a separate download keeps on getting killed by the OOM-killer (mem usage gets around 50%). Tweaking with some OOM-killer settings and stopping AlienDalvik for more memory did not help.
I am writing to an sdcard (class 10), but the download is faster than the writing, which may create a buffer.
Version 0.7.0 did not present timeouts, but also suffered memory issues (app crash).
The timeouts may be related to waits for writes, the internet connection is good.

**Comment by rinigus** [comment]
Thank you for opening the issue. If our suspicion is right that there are buffers involved, it should not be too hard to fix. 

Note to myself mainly: I just have to think how to handle the case where I stop reading from network stream to throttle the traffic using http://doc.qt.io/qt-5/qnetworkreply.html#setReadBufferSize . In addition, timeouts should be checked against stream going into file as well.

**Comment by rinigus** [comment]
It looks that by using QIODevice::bytesWritten(qint64 bytes) / QIODevice::bytesToWrite() its possible to monitor state of the buffers before consumed by bunzip2 and file i/o. 

I guess, I should set max sizes for network read buffer and accept new data from network interface only if file and process buffers are below some limit. A simple implementation would be to check them just periodically. Alternative is to hook to signal bytesWritten emitted by qprocess and qfile.

As for timeouts, it should be reset every time something is written to file as well.

**Comment by rinigus** [comment]
I hope the last commit would fix your problem. I am following the sizes of the buffers between network -> bunzip2 -> file and pause reading network stream if the buffers get big (more than few MB).

If you could test whether the build attached to this message would help you out? I had to attach it as ZIP since GitHub does not support RPM type.

Looking forward for your test results!

[test.zip](https://github.com/rinigus/osmscout-server/files/835226/test.zip)

**Comment by a-dekker** [comment]
Sorry to say it does not help.
On the positive site: no more timeout messages.
But the memory usage keeps on growing, until the message "OSM Scout Server is not responding" appears and the app crashes.

```
# rpm -qa|grep osmscout
harbour-osmscout-server-0.7.1-1.armv7hl
```

A memory query during download (ps_mem.py):
```
 Private  +   Shared  =  RAM used       Program 
382.3 MiB +   5.3 MiB = 387.6 MiB       harbour-osmscou

```
Memory usage just before the crash:
ps aux, fourth column is percentage of total memory used
`nemo     28095 18.6 54.3 848084 450052 ?       Rsl  23:27   1:17 /usr/bin/harbour-osmscout-server`

**Comment by rinigus** [comment]
Hi again,

OK, looks to be a bit more complicated. Namely, it seems that Qt ignores network reply settings for the first download possibly leading to huge RAM consumption. Second download is fine though. So, I keep tabs now on network-related buffer size and restart the download if its too large. Let's see if it helps. There is also an option now in configuration file (no GUI) that allows to throttle download, but let's not use it for now.

I prepared a new RPM with debug messages printing out the state of the buffers. Would you mind to try with the attached version and run it on terminal:

```
harbour-osmscout-server > output 2>&1
```

Let's see if it helps. Would be great to see output log from your download as well, please attach it here.

[harbour-osmscout-server-0.7.1-1.armv7hl-test.zip](https://github.com/rinigus/osmscout-server/files/835637/harbour-osmscout-server-0.7.1-1.armv7hl-test.zip)

**Comment by a-dekker** [comment]
I'm not sure if the log output has any influence, but it works fine now (from the commandline, with or without redirecting to a file).
The memory usage is 6.5% of the total memory at max.
The log is about 60MB, but I am afraid it is of no use in this case.

**Comment by rinigus** [comment]
Brilliant!!!! Let's skip the log then :) Thank you very much for reporting and helping to fix it with the fast testing!

**Comment by rinigus** [comment]
PS: Don't forget to select languages in geocoder-nlp - otherwise you will get the next OOM-killer!

**Comment by a-dekker** [comment]
Still wondering what the big difference is, but for now it works fine for me.
Thanks rinigus!

**Comment by rinigus** [comment]
Welcome!

The problem was in huge network buffer. Qt provides classes to download via HTTP. One of them, QNetworkReply allows you to limit reading buffer via setReadBufferSize method. It is expected that if you don't read data from QNetworkReply object, it would stop downloading if this buffer is full. I used that and did not read the data from QNetworkReply object when memory buffers downstream were getting bigger (bunzip2 and file writing). That was the state yesterday night and it all failed at your first test.

Turned out that Qt ignored setting of setReadBufferSize for the first download. I guess its a bug in Qt 5.2, maybe even later as well. As a result, while I was not reading any data from QNetworkReply object, it was still happily downloading it and allocating more and more RAM. 

The fix today was to follow read buffer in QNetworkReply object and when it gets more than 10MB, cancel the download and start again. On my phone it worked nicely and it looks its the same on yours. Its rather robust approach, but it seems to be the only way around this Qt bug/feature.

I am going to close this bug and let's reopen it if we see the same problem later :)
